/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/book-search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Books */
    get: operations["search_books_api_v1_book_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/book-search/isbn/{isbn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Book By Isbn */
    get: operations["search_book_by_isbn_api_v1_book_search_isbn__isbn__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_api_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Readers */
    get: operations["list_readers_api_v1_readers_get"];
    put?: never;
    /** Create Reader */
    post: operations["create_reader_api_v1_readers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readers/{reader_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Reader */
    get: operations["get_reader_api_v1_readers__reader_id__get"];
    put?: never;
    post?: never;
    /** Delete Reader */
    delete: operations["delete_reader_api_v1_readers__reader_id__delete"];
    options?: never;
    head?: never;
    /** Update Reader */
    patch: operations["update_reader_api_v1_readers__reader_id__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BookSearchResult */
    BookSearchResult: {
      /** Authors */
      authors?: string[];
      /** Cover Url */
      cover_url?: string | null;
      /** Description */
      description?: string | null;
      /** External Source Id */
      external_source_id: string;
      /** Isbn 10 */
      isbn_10?: string | null;
      /** Isbn 13 */
      isbn_13?: string | null;
      /** Language */
      language?: string | null;
      /** Page Count */
      page_count?: number | null;
      /** Published Date */
      published_date?: string | null;
      /** Publisher */
      publisher?: string | null;
      source: components["schemas"]["MetadataSource"];
      /** Subtitle */
      subtitle?: string | null;
      /** Title */
      title: string;
    };
    /** CurrentUserResponse */
    CurrentUserResponse: {
      /** Email */
      email: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /** Household Name */
      household_name: string;
      role: components["schemas"]["HouseholdRole"];
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /**
     * HouseholdRole
     * @enum {string}
     */
    HouseholdRole: "owner" | "caregiver";
    /**
     * MetadataSource
     * @enum {string}
     */
    MetadataSource: "manual" | "google_books" | "open_library";
    /** ReaderCreate */
    ReaderCreate: {
      /** Avatar Key */
      avatar_key?: string | null;
      /** Name */
      name: string;
    };
    /** ReaderResponse */
    ReaderResponse: {
      /** Avatar Key */
      avatar_key: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReaderUpdate */
    ReaderUpdate: {
      /** Avatar Key */
      avatar_key?: string | null;
      /** Name */
      name?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  search_books_api_v1_book_search_get: {
    parameters: {
      query?: {
        q?: string | null;
        title?: string | null;
        author?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookSearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_book_by_isbn_api_v1_book_search_isbn__isbn__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        isbn: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookSearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  get_me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
    };
  };
  list_readers_api_v1_readers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"][];
        };
      };
    };
  };
  create_reader_api_v1_readers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_reader_api_v1_readers__reader_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_reader_api_v1_readers__reader_id__delete: {
    parameters: {
      query?: {
        confirm_history?: boolean;
      };
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_reader_api_v1_readers__reader_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
