/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/book-recommendations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Book Recommendations */
    get: operations["list_book_recommendations_api_v1_book_recommendations_get"];
    put?: never;
    /** Create Book Recommendation */
    post: operations["create_book_recommendation_api_v1_book_recommendations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/book-recommendations/{recommendation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Book Recommendation */
    delete: operations["delete_book_recommendation_api_v1_book_recommendations__recommendation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/book-search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Books */
    get: operations["search_books_api_v1_book_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/book-search/isbn/{isbn}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Book By Isbn */
    get: operations["search_book_by_isbn_api_v1_book_search_isbn__isbn__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/books": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Books */
    get: operations["list_books_api_v1_books_get"];
    put?: never;
    /** Create Book */
    post: operations["create_book_api_v1_books_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/books/{book_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Book */
    get: operations["get_book_api_v1_books__book_id__get"];
    put?: never;
    post?: never;
    /** Delete Book */
    delete: operations["delete_book_api_v1_books__book_id__delete"];
    options?: never;
    head?: never;
    /** Update Book */
    patch: operations["update_book_api_v1_books__book_id__patch"];
    trace?: never;
  };
  "/api/v1/caregiver-login-invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Caregiver Invitations */
    get: operations["list_caregiver_invitations_api_v1_caregiver_login_invitations_get"];
    put?: never;
    /** Create Caregiver Invitation */
    post: operations["create_caregiver_invitation_api_v1_caregiver_login_invitations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/caregiver-login-invitations/{invitation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Caregiver Invitation */
    delete: operations["delete_caregiver_invitation_api_v1_caregiver_login_invitations__invitation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/exports/reading-data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Reading Data */
    get: operations["export_reading_data_api_v1_exports_reading_data_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/exports/school-reading-report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export School Reading Report */
    get: operations["export_school_reading_report_api_v1_exports_school_reading_report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_api_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reader-login-invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Invitations */
    get: operations["list_invitations_api_v1_reader_login_invitations_get"];
    put?: never;
    /** Create Invitation */
    post: operations["create_invitation_api_v1_reader_login_invitations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reader-login-invitations/{invitation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Invitation */
    delete: operations["delete_invitation_api_v1_reader_login_invitations__invitation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Readers */
    get: operations["list_readers_api_v1_readers_get"];
    put?: never;
    /** Create Reader */
    post: operations["create_reader_api_v1_readers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readers/{reader_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Reader */
    get: operations["get_reader_api_v1_readers__reader_id__get"];
    put?: never;
    post?: never;
    /** Delete Reader */
    delete: operations["delete_reader_api_v1_readers__reader_id__delete"];
    options?: never;
    head?: never;
    /** Update Reader */
    patch: operations["update_reader_api_v1_readers__reader_id__patch"];
    trace?: never;
  };
  "/api/v1/readers/{reader_id}/books": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Book To Reader */
    post: operations["add_book_to_reader_api_v1_readers__reader_id__books_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readers/{reader_id}/books/{book_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Reader Book */
    delete: operations["remove_reader_book_api_v1_readers__reader_id__books__book_id__delete"];
    options?: never;
    head?: never;
    /** Update Reader Book */
    patch: operations["update_reader_book_api_v1_readers__reader_id__books__book_id__patch"];
    trace?: never;
  };
  "/api/v1/reading-sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reading Sessions */
    get: operations["list_reading_sessions_api_v1_reading_sessions_get"];
    put?: never;
    /** Create Reading Session */
    post: operations["create_reading_session_api_v1_reading_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reading-sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Reading Session */
    get: operations["get_reading_session_api_v1_reading_sessions__session_id__get"];
    put?: never;
    post?: never;
    /** Delete Reading Session */
    delete: operations["delete_reading_session_api_v1_reading_sessions__session_id__delete"];
    options?: never;
    head?: never;
    /** Update Reading Session */
    patch: operations["update_reading_session_api_v1_reading_sessions__session_id__patch"];
    trace?: never;
  };
  "/api/v1/reports/calendar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Calendar Report */
    get: operations["get_calendar_report_api_v1_reports_calendar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Report Summary */
    get: operations["get_report_summary_api_v1_reports_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reward-items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reward Items */
    get: operations["list_reward_items_api_v1_reward_items_get"];
    put?: never;
    /** Create Reward Item */
    post: operations["create_reward_item_api_v1_reward_items_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reward-items/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Reward Item */
    delete: operations["delete_reward_item_api_v1_reward_items__item_id__delete"];
    options?: never;
    head?: never;
    /** Update Reward Item */
    patch: operations["update_reward_item_api_v1_reward_items__item_id__patch"];
    trace?: never;
  };
  "/api/v1/reward-redemptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reward Redemptions */
    get: operations["list_reward_redemptions_api_v1_reward_redemptions_get"];
    put?: never;
    /** Redeem Reward */
    post: operations["redeem_reward_api_v1_reward_redemptions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reward-redemptions/{redemption_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Transition Redemption */
    patch: operations["transition_redemption_api_v1_reward_redemptions__redemption_id__patch"];
    trace?: never;
  };
  "/api/v1/rewards/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Reward Progress */
    get: operations["get_reward_progress_api_v1_rewards_progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rewards/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reward Transactions */
    get: operations["list_reward_transactions_api_v1_rewards_transactions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActivityType
     * @enum {string}
     */
    ActivityType: "independent" | "with_adult" | "read_aloud" | "audiobook";
    /** BadgeProgress */
    BadgeProgress: {
      /**
       * Badge Id
       * Format: uuid
       */
      badge_id: string;
      /** Category */
      category: string;
      /** Code */
      code: string;
      /** Credit Value */
      credit_value: number;
      /** Current Value */
      current_value: number;
      /** Description */
      description: string;
      /** Earned */
      earned: boolean;
      /** Earned At */
      earned_at: string | null;
      /** Name */
      name: string;
      /** Progress Percent */
      progress_percent: number;
      /** Threshold */
      threshold: number;
    };
    /** BookCreate */
    BookCreate: {
      /** Authors */
      authors?: string[];
      /** Cover Url */
      cover_url?: string | null;
      /** Description */
      description?: string | null;
      /** External Source Id */
      external_source_id?: string | null;
      /** Isbn 10 */
      isbn_10?: string | null;
      /** Isbn 13 */
      isbn_13?: string | null;
      /** Language */
      language?: string | null;
      /** @default manual */
      metadata_source: components["schemas"]["MetadataSource"];
      /** Page Count */
      page_count?: number | null;
      /** Published Date */
      published_date?: string | null;
      /** Publisher */
      publisher?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Title */
      title: string;
    };
    /** BookRecommendationCreate */
    BookRecommendationCreate: {
      book: components["schemas"]["BookCreate"];
      /** Note */
      note?: string | null;
    };
    /** BookRecommendationResponse */
    BookRecommendationResponse: {
      book: components["schemas"]["BookResponse"];
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** BookResponse */
    BookResponse: {
      /** Authors */
      authors?: string[];
      /** Cover Url */
      cover_url?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description?: string | null;
      /** External Source Id */
      external_source_id?: string | null;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Isbn 10 */
      isbn_10?: string | null;
      /** Isbn 13 */
      isbn_13?: string | null;
      /** Language */
      language?: string | null;
      /** @default manual */
      metadata_source: components["schemas"]["MetadataSource"];
      /** Page Count */
      page_count?: number | null;
      /** Published Date */
      published_date?: string | null;
      /** Publisher */
      publisher?: string | null;
      /** Reader Books */
      reader_books?: components["schemas"]["ReaderBookResponse"][];
      /** Subtitle */
      subtitle?: string | null;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** BookSearchResult */
    BookSearchResult: {
      /** Authors */
      authors?: string[];
      /** Cover Url */
      cover_url?: string | null;
      /** Description */
      description?: string | null;
      /** External Source Id */
      external_source_id: string;
      /** Isbn 10 */
      isbn_10?: string | null;
      /** Isbn 13 */
      isbn_13?: string | null;
      /** Language */
      language?: string | null;
      /** Page Count */
      page_count?: number | null;
      /** Published Date */
      published_date?: string | null;
      /** Publisher */
      publisher?: string | null;
      source: components["schemas"]["MetadataSource"];
      /** Subtitle */
      subtitle?: string | null;
      /** Title */
      title: string;
    };
    /** BookUpdate */
    BookUpdate: {
      /** Authors */
      authors?: string[] | null;
      /** Cover Url */
      cover_url?: string | null;
      /** Description */
      description?: string | null;
      /** Isbn 10 */
      isbn_10?: string | null;
      /** Isbn 13 */
      isbn_13?: string | null;
      /** Language */
      language?: string | null;
      /** Page Count */
      page_count?: number | null;
      /** Published Date */
      published_date?: string | null;
      /** Publisher */
      publisher?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Title */
      title?: string | null;
    };
    /** CalendarDay */
    CalendarDay: {
      /** Books Finished */
      books_finished: number;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Minutes */
      minutes: number;
      /** Pages Read */
      pages_read: number;
      /** Sessions Count */
      sessions_count: number;
    };
    /** CalendarReportResponse */
    CalendarReportResponse: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Days */
      days: components["schemas"]["CalendarDay"][];
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
    };
    /** CaregiverLoginInvitationCreate */
    CaregiverLoginInvitationCreate: {
      /** Email */
      email: string;
    };
    /** CaregiverLoginInvitationResponse */
    CaregiverLoginInvitationResponse: {
      /** Accepted */
      accepted: boolean;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** CurrentBookProgress */
    CurrentBookProgress: {
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /** Cover Url */
      cover_url: string | null;
      /** Last Page */
      last_page: number | null;
      /** Page Count */
      page_count: number | null;
      /** Progress Percent */
      progress_percent: number | null;
      status: components["schemas"]["ReadingStatus"];
      /** Title */
      title: string;
    };
    /** CurrentUserResponse */
    CurrentUserResponse: {
      /** Email */
      email: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /** Household Name */
      household_name: string;
      /** Is Admin */
      is_admin: boolean;
      /** Reader Id */
      reader_id: string | null;
      role: components["schemas"]["HouseholdRole"];
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** ExportBadgeDefinition */
    ExportBadgeDefinition: {
      /** Active */
      active: boolean;
      /** Category */
      category: string;
      /** Code */
      code: string;
      /** Credit Value */
      credit_value: number;
      /** Description */
      description: string;
      /** Display Order */
      display_order: number;
      /** Icon Key */
      icon_key: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Threshold */
      threshold: number;
    };
    /** ExportBook */
    ExportBook: {
      /** Authors */
      authors: string[];
      /** Cover Url */
      cover_url: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string | null;
      /** External Source Id */
      external_source_id: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Isbn 10 */
      isbn_10: string | null;
      /** Isbn 13 */
      isbn_13: string | null;
      /** Language */
      language: string | null;
      metadata_source: components["schemas"]["MetadataSource"];
      /** Page Count */
      page_count: number | null;
      /** Published Date */
      published_date: string | null;
      /** Publisher */
      publisher: string | null;
      /** Subtitle */
      subtitle: string | null;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportReader */
    ExportReader: {
      /** Avatar Key */
      avatar_key: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportReaderBadge */
    ExportReaderBadge: {
      /**
       * Badge Definition Id
       * Format: uuid
       */
      badge_definition_id: string;
      /**
       * Earned At
       * Format: date-time
       */
      earned_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Progress Value */
      progress_value: number;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Revocation Reason */
      revocation_reason: string | null;
      /** Revoked At */
      revoked_at: string | null;
    };
    /** ExportReaderBook */
    ExportReaderBook: {
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["ReadingStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportReadingSession */
    ExportReadingSession: {
      activity_type: components["schemas"]["ActivityType"];
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** End Page */
      end_page: number | null;
      /** Finished Book */
      finished_book: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Minutes */
      minutes: number;
      /** Notes */
      notes: string | null;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Start Page */
      start_page: number | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportRewardItem */
    ExportRewardItem: {
      /** Active */
      active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Credit Cost */
      credit_cost: number;
      /** Deleted At */
      deleted_at: string | null;
      /** Description */
      description: string | null;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Quantity */
      quantity: number | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportRewardRedemption */
    ExportRewardRedemption: {
      /** Approved At */
      approved_at: string | null;
      /** Cancelled At */
      cancelled_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Credit Cost */
      credit_cost: number;
      /** Fulfilled At */
      fulfilled_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Parent Notes */
      parent_notes: string | null;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /**
       * Reward Item Id
       * Format: uuid
       */
      reward_item_id: string;
      /** Reward Name */
      reward_name: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExportRewardTransaction */
    ExportRewardTransaction: {
      /** Amount */
      amount: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Source Id */
      source_id: string | null;
      /** Transaction Type */
      transaction_type: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /**
     * HouseholdRole
     * @enum {string}
     */
    HouseholdRole: "owner" | "caregiver" | "reader";
    /**
     * MetadataSource
     * @enum {string}
     */
    MetadataSource: "manual" | "google_books" | "open_library";
    /** ReaderBookCreate */
    ReaderBookCreate: {
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /** Finished At */
      finished_at?: string | null;
      /** Started At */
      started_at?: string | null;
      /** @default planned */
      status: components["schemas"]["ReadingStatus"];
    };
    /** ReaderBookResponse */
    ReaderBookResponse: {
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["ReadingStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReaderBookUpdate */
    ReaderBookUpdate: {
      /** Finished At */
      finished_at?: string | null;
      /** Started At */
      started_at?: string | null;
      status?: components["schemas"]["ReadingStatus"] | null;
    };
    /** ReaderCreate */
    ReaderCreate: {
      /** Avatar Key */
      avatar_key?: string | null;
      /** Name */
      name: string;
    };
    /** ReaderLoginInvitationCreate */
    ReaderLoginInvitationCreate: {
      /** Email */
      email: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
    };
    /** ReaderLoginInvitationResponse */
    ReaderLoginInvitationResponse: {
      /** Accepted */
      accepted: boolean;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
    };
    /** ReaderResponse */
    ReaderResponse: {
      /** Avatar Key */
      avatar_key: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReaderUpdate */
    ReaderUpdate: {
      /** Avatar Key */
      avatar_key?: string | null;
      /** Name */
      name?: string | null;
    };
    /** ReadingDataExport */
    ReadingDataExport: {
      /** Badge Definitions */
      badge_definitions: components["schemas"]["ExportBadgeDefinition"][];
      /** Books */
      books: components["schemas"]["ExportBook"][];
      /**
       * Exported At
       * Format: date-time
       */
      exported_at: string;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /** Household Name */
      household_name: string;
      /** Reader Badges */
      reader_badges: components["schemas"]["ExportReaderBadge"][];
      /** Reader Books */
      reader_books: components["schemas"]["ExportReaderBook"][];
      /** Readers */
      readers: components["schemas"]["ExportReader"][];
      /** Reading Sessions */
      reading_sessions: components["schemas"]["ExportReadingSession"][];
      /** Reward Items */
      reward_items: components["schemas"]["ExportRewardItem"][];
      /** Reward Redemptions */
      reward_redemptions: components["schemas"]["ExportRewardRedemption"][];
      /** Reward Transactions */
      reward_transactions: components["schemas"]["ExportRewardTransaction"][];
      /**
       * Schema Version
       * @default 2
       */
      schema_version: number;
    };
    /** ReadingSessionCreate */
    ReadingSessionCreate: {
      activity_type: components["schemas"]["ActivityType"];
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /** End Page */
      end_page?: number | null;
      /**
       * Finished Book
       * @default false
       */
      finished_book: boolean;
      /** Minutes */
      minutes: number;
      /** Notes */
      notes?: string | null;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Start Page */
      start_page?: number | null;
    };
    /** ReadingSessionResponse */
    ReadingSessionResponse: {
      activity_type: components["schemas"]["ActivityType"];
      /** Book Cover Url */
      book_cover_url: string | null;
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /** Book Title */
      book_title: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** End Page */
      end_page: number | null;
      /** Finished Book */
      finished_book: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Minutes */
      minutes: number;
      /** Notes */
      notes: string | null;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
      /** Start Page */
      start_page: number | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReadingSessionUpdate */
    ReadingSessionUpdate: {
      activity_type?: components["schemas"]["ActivityType"] | null;
      /** End Page */
      end_page?: number | null;
      /** Finished Book */
      finished_book?: boolean | null;
      /** Minutes */
      minutes?: number | null;
      /** Notes */
      notes?: string | null;
      /** Session Date */
      session_date?: string | null;
      /** Start Page */
      start_page?: number | null;
    };
    /**
     * ReadingStatus
     * @enum {string}
     */
    ReadingStatus: "planned" | "reading" | "finished";
    /** RedemptionAction */
    RedemptionAction: {
      /** Parent Notes */
      parent_notes?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "approved" | "rejected" | "fulfilled" | "cancelled";
    };
    /** RedemptionCreate */
    RedemptionCreate: {
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Reward Item Id
       * Format: uuid
       */
      reward_item_id: string;
    };
    /** RedemptionResponse */
    RedemptionResponse: {
      /** Approved At */
      approved_at: string | null;
      /** Cancelled At */
      cancelled_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Credit Cost */
      credit_cost: number;
      /** Fulfilled At */
      fulfilled_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Parent Notes */
      parent_notes: string | null;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /**
       * Reward Item Id
       * Format: uuid
       */
      reward_item_id: string;
      /** Reward Name */
      reward_name: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ReportSession */
    ReportSession: {
      activity_type: components["schemas"]["ActivityType"];
      /** Book Cover Url */
      book_cover_url: string | null;
      /**
       * Book Id
       * Format: uuid
       */
      book_id: string;
      /** Book Title */
      book_title: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Finished Book */
      finished_book: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Minutes */
      minutes: number;
      /** Pages Read */
      pages_read: number;
      /**
       * Session Date
       * Format: date
       */
      session_date: string;
    };
    /** ReportSummaryResponse */
    ReportSummaryResponse: {
      /** Books Finished */
      books_finished: number;
      /** Current Books */
      current_books: components["schemas"]["CurrentBookProgress"][];
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Pages Read */
      pages_read: number;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Reading Days */
      reading_days: number;
      /** Recent Activity */
      recent_activity: components["schemas"]["ReportSession"][];
      /** Sessions Count */
      sessions_count: number;
      /** Total Minutes */
      total_minutes: number;
    };
    /** RewardItemCreate */
    RewardItemCreate: {
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Credit Cost */
      credit_cost: number;
      /** Description */
      description?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Name */
      name: string;
      /** Quantity */
      quantity?: number | null;
    };
    /** RewardItemResponse */
    RewardItemResponse: {
      /** Active */
      active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Credit Cost */
      credit_cost: number;
      /** Deleted At */
      deleted_at: string | null;
      /** Description */
      description: string | null;
      /**
       * Household Id
       * Format: uuid
       */
      household_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Quantity */
      quantity: number | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** RewardItemUpdate */
    RewardItemUpdate: {
      /** Active */
      active?: boolean | null;
      /** Credit Cost */
      credit_cost?: number | null;
      /** Description */
      description?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Name */
      name?: string | null;
      /** Quantity */
      quantity?: number | null;
    };
    /** RewardProgressResponse */
    RewardProgressResponse: {
      /** Badges */
      badges: components["schemas"]["BadgeProgress"][];
      /** Credit Balance */
      credit_balance: number;
      /** Current Continuous Days */
      current_continuous_days: number;
      /** Current Week Reading Days */
      current_week_reading_days: number;
      /** Current Weekly Streak */
      current_weekly_streak: number;
      /** Finished Books */
      finished_books: number;
      /** Longest Continuous Days */
      longest_continuous_days: number;
      /** Longest Weekly Streak */
      longest_weekly_streak: number;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
    };
    /** RewardTransactionResponse */
    RewardTransactionResponse: {
      /** Amount */
      amount: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Reader Id
       * Format: uuid
       */
      reader_id: string;
      /** Source Id */
      source_id: string | null;
      /** Transaction Type */
      transaction_type: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_book_recommendations_api_v1_book_recommendations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookRecommendationResponse"][];
        };
      };
    };
  };
  create_book_recommendation_api_v1_book_recommendations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookRecommendationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookRecommendationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_book_recommendation_api_v1_book_recommendations__recommendation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recommendation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_books_api_v1_book_search_get: {
    parameters: {
      query?: {
        q?: string | null;
        title?: string | null;
        author?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookSearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_book_by_isbn_api_v1_book_search_isbn__isbn__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        isbn: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookSearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_books_api_v1_books_get: {
    parameters: {
      query?: {
        reader_id?: string | null;
        status?: components["schemas"]["ReadingStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_book_api_v1_books_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_book_api_v1_books__book_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        book_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_book_api_v1_books__book_id__delete: {
    parameters: {
      query?: {
        confirm_history?: boolean;
      };
      header?: never;
      path: {
        book_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_book_api_v1_books__book_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        book_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_caregiver_invitations_api_v1_caregiver_login_invitations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaregiverLoginInvitationResponse"][];
        };
      };
    };
  };
  create_caregiver_invitation_api_v1_caregiver_login_invitations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaregiverLoginInvitationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaregiverLoginInvitationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_caregiver_invitation_api_v1_caregiver_login_invitations__invitation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_reading_data_api_v1_exports_reading_data_get: {
    parameters: {
      query?: {
        format?: "json" | "csv" | "finished-books-csv";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Complete JSON backup, reading-session CSV, or finished-books CSV */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadingDataExport"];
          "text/csv": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_school_reading_report_api_v1_exports_school_reading_report_get: {
    parameters: {
      query: {
        reader_id: string;
        date_from: string;
        date_to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Printable school reading achievement report */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "application/pdf": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  get_me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
    };
  };
  list_invitations_api_v1_reader_login_invitations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderLoginInvitationResponse"][];
        };
      };
    };
  };
  create_invitation_api_v1_reader_login_invitations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderLoginInvitationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderLoginInvitationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_invitation_api_v1_reader_login_invitations__invitation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_readers_api_v1_readers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"][];
        };
      };
    };
  };
  create_reader_api_v1_readers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_reader_api_v1_readers__reader_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_reader_api_v1_readers__reader_id__delete: {
    parameters: {
      query?: {
        confirm_history?: boolean;
      };
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_reader_api_v1_readers__reader_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_book_to_reader_api_v1_readers__reader_id__books_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderBookCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderBookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_reader_book_api_v1_readers__reader_id__books__book_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
        book_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_reader_book_api_v1_readers__reader_id__books__book_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        reader_id: string;
        book_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReaderBookUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReaderBookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reading_sessions_api_v1_reading_sessions_get: {
    parameters: {
      query?: {
        reader_id?: string | null;
        book_id?: string | null;
        activity_type?: components["schemas"]["ActivityType"] | null;
        date_from?: string | null;
        date_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadingSessionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_reading_session_api_v1_reading_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReadingSessionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadingSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_reading_session_api_v1_reading_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadingSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_reading_session_api_v1_reading_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_reading_session_api_v1_reading_sessions__session_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReadingSessionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadingSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_calendar_report_api_v1_reports_calendar_get: {
    parameters: {
      query: {
        reader_id: string;
        date_from: string;
        date_to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CalendarReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_report_summary_api_v1_reports_summary_get: {
    parameters: {
      query: {
        reader_id: string;
        date_from: string;
        date_to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportSummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reward_items_api_v1_reward_items_get: {
    parameters: {
      query?: {
        include_inactive?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RewardItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_reward_item_api_v1_reward_items_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RewardItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RewardItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_reward_item_api_v1_reward_items__item_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_reward_item_api_v1_reward_items__item_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RewardItemUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RewardItemResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reward_redemptions_api_v1_reward_redemptions_get: {
    parameters: {
      query: {
        reader_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RedemptionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  redeem_reward_api_v1_reward_redemptions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RedemptionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RedemptionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transition_redemption_api_v1_reward_redemptions__redemption_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        redemption_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RedemptionAction"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RedemptionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_reward_progress_api_v1_rewards_progress_get: {
    parameters: {
      query: {
        reader_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RewardProgressResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reward_transactions_api_v1_rewards_transactions_get: {
    parameters: {
      query: {
        reader_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RewardTransactionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
